const products = [
    { id: "KING_365", name: "KING 365", price: 55.0, images: ["https://www.iptv-store.shop/KING365.png", "http://bit.ly/3VGWWLD", "http://bit.ly/4nZQLOP", "http://bit.ly/48FoOHy", "http://bit.ly/4npB9Eg"], description: "Abonnement IPTV Premium de haute qualité...", serverTypes: ["xtream", "m3u", "mag"], category: "Premium" },
    {
        id: "IRON_TV_MAX",
        name: "IRON TV MAX",
        price: 40.0,
        images: ["https://www.iptv-store.shop/IRON.png", "https://bit.ly/3KhqEUV", "https://bit.ly/47ZNavj", "http://bit.ly/3VMojnv", "http://bit.ly/3WgtCLY"],
        description: "Le choix idéal pour les amateurs de sport...",
        serverTypes: ["code active", "xtream", "m3u", "mag"],
        category: "Premium",
    },
    {
        id: "NEO4K",
        name: "NEO4K",
        price: 45.0,
        images: ["https://www.iptv-store.shop/neo4k.png"],
        description: "Profitez d'une qualité d'image époustouflante en 4K.",
        serverTypes: ["code active", "xtream", "m3u", "mag"],
        category: "Haute Qualité",
    },
    {
        id: "ATLAS_PRO",
        name: "ATLAS PRO",
        price: 29.0,
        images: ["https://www.iptv-store.shop/ATLAS.png"],
        description:
            "Atlas Pro IPTV est votre porte d’entrée vers un divertissement illimité, profitez de milliers de chaînes de France, d’Espagne, d’Allemagne, de Belgique, de chaînes arabes et du monde entier. Ainsi que les derniers films et séries.",
        serverTypes: ["code active", "xtream", "m3u", "mag"],
        category: "Standard",
    },
    { id: "FOSTO", name: "FOSTO", price: 25.0, images: ["https://www.iptv-store.shop/FOSTO.png", "http://bit.ly/42kz1Fx", "http://bit.ly/4pO4M3K", "http://bit.ly/4pKQUap", "http://bit.ly/4pMdqjr"], description: "Solution IPTV stable et riche en contenu...", serverTypes: ["code active", "xtream", "m3u", "mag"], category: "Standard" },
    { id: "LYNX", name: "LYNX", price: 25.0, images: ["https://www.iptv-store.shop/LYNX.png"], description: "Abonnement IPTV polyvalent et abordable...", serverTypes: ["code active", "xtream", "m3u", "mag"], category: "Standard" },
    {
        id: "QHDTV",
        name: "QHDTV",
        price: 30.0,
        images: ["https://www.iptv-store.shop/QHDTV.png", "https://bit.ly/4gUBtbN"],
        description: "Qualité HD supérieure pour un visionnage clair...",
        serverTypes: ["code active", "xtream", "m3u", "mag"],
        category: "Haute Qualité",
    },
    { id: "IBO", name: "IBO", price: 35.0, images: ["https://www.iptv-store.shop/IBO.png"], description: "IBO Player est une application populaire...", serverTypes: ["code active", "xtream", "m3u", "mag"], category: "Applications" },
    {
        id: "SMARTERS_PLAYER",
        name: "SMARTERS PLAYER",
        price: 30.0,
        images: ["https://www.iptv-store.shop/SMARTERS-PLAYER.png", "https://bit.ly/4nycU72"],
        description: "Smarters Player est une application IPTV robuste...",
        serverTypes: ["code active", "xtream", "m3u", "mag"],
        category: "Applications",
    },
];
